# Generated by Django 5.0.1 on 2024-02-22 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_posted_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 22, 14, 50, 22, 458938), null=True),
        ),
    ]
